version: '3.7'
services:
  web:
    build: .
    entrypoint: entrypoint.sh
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dog-api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=dog_api_development
      - POSTGRES_PASSWORD=dog_api_development
volumes:
  postgres_data:
