default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  database: dog_api_development
  password: dog_api_development

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: dog_api_production
  username: dog_api
  password: dog_api
